# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'labels_settings_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_labels_settings(object):
    def setupUi(self, labels_settings):
        labels_settings.setObjectName("labels_settings")
        labels_settings.resize(790, 567)
        self.centralwidget = QtWidgets.QWidget(labels_settings)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.open = QtWidgets.QPushButton(self.centralwidget)
        self.open.setStyleSheet("QPushButton {\n"
"    background-color: #455364; /* 默认颜色，浅灰色 */\n"
"    border: 1px solid #666666; /* 灰色的边框 */\n"
"    padding: 5px 10px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #54687a; /* 鼠标悬停时的颜色，稍浅的灰色 */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #455364; /* 鼠标点击时的颜色，稍深的灰色 */\n"
"}\n"
"")
        self.open.setObjectName("open")
        self.horizontalLayout_4.addWidget(self.open)
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setStyleSheet("QPushButton {\n"
"    background-color: #455364; /* 默认颜色，浅灰色 */\n"
"    border: 1px solid #666666; /* 灰色的边框 */\n"
"    padding: 5px 10px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #54687a; /* 鼠标悬停时的颜色，稍浅的灰色 */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #455364; /* 鼠标点击时的颜色，稍深的灰色 */\n"
"}\n"
"")
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_4.addWidget(self.pushButton)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.models_list = QtWidgets.QListWidget(self.centralwidget)
        self.models_list.setObjectName("models_list")
        self.verticalLayout.addWidget(self.models_list)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setAutoFillBackground(False)
        self.pushButton_2.setStyleSheet("QPushButton {\n"
"    background-color: #455364; /* 默认颜色，浅灰色 */\n"
"    border: 1px solid #666666; /* 灰色的边框 */\n"
"    padding: 5px 10px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #54687a; /* 鼠标悬停时的颜色，稍浅的灰色 */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #455364; /* 鼠标点击时的颜色，稍深的灰色 */\n"
"}\n"
"")
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout_2.addWidget(self.pushButton_2)
        self.delete_2 = QtWidgets.QPushButton(self.centralwidget)
        self.delete_2.setStyleSheet("QPushButton {\n"
"    background-color: #455364; /* 默认颜色，浅灰色 */\n"
"    border: 1px solid #666666; /* 灰色的边框 */\n"
"    padding: 5px 10px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #54687a; /* 鼠标悬停时的颜色，稍浅的灰色 */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #455364; /* 鼠标点击时的颜色，稍深的灰色 */\n"
"}\n"
"")
        self.delete_2.setObjectName("delete_2")
        self.horizontalLayout_2.addWidget(self.delete_2)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.sets_list = QtWidgets.QListWidget(self.centralwidget)
        self.sets_list.setObjectName("sets_list")
        self.verticalLayout.addWidget(self.sets_list)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.verticalLayout.setStretch(1, 1)
        self.verticalLayout.setStretch(3, 10)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents_3 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_3.setGeometry(QtCore.QRect(0, 0, 504, 525))
        self.scrollAreaWidgetContents_3.setObjectName("scrollAreaWidgetContents_3")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents_3)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.fan = QtWidgets.QPushButton(self.scrollAreaWidgetContents_3)
        self.fan.setObjectName("fan")
        self.horizontalLayout_6.addWidget(self.fan)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem)
        self.verticalLayout_2.addLayout(self.horizontalLayout_6)
        self.labels_part_2 = QtWidgets.QVBoxLayout()
        self.labels_part_2.setContentsMargins(-1, 0, -1, -1)
        self.labels_part_2.setObjectName("labels_part_2")
        self.verticalLayout_2.addLayout(self.labels_part_2)
        self.verticalLayout_2.setStretch(0, 1)
        self.verticalLayout_2.setStretch(1, 10)
        self.gridLayout_2.addLayout(self.verticalLayout_2, 0, 0, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents_3)
        self.horizontalLayout.addWidget(self.scrollArea)
        self.horizontalLayout.setStretch(1, 2)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        labels_settings.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(labels_settings)
        self.statusbar.setObjectName("statusbar")
        labels_settings.setStatusBar(self.statusbar)

        self.retranslateUi(labels_settings)
        QtCore.QMetaObject.connectSlotsByName(labels_settings)

    def retranslateUi(self, labels_settings):
        _translate = QtCore.QCoreApplication.translate
        labels_settings.setWindowTitle(_translate("labels_settings", "MainWindow"))
        self.open.setText(_translate("labels_settings", "打开文件夹"))
        self.pushButton.setToolTip(_translate("labels_settings", "显示内容"))
        self.pushButton.setText(_translate("labels_settings", "显示内容"))
        self.pushButton_2.setToolTip(_translate("labels_settings", "新建"))
        self.pushButton_2.setText(_translate("labels_settings", "新建"))
        self.delete_2.setToolTip(_translate("labels_settings", "删除"))
        self.delete_2.setText(_translate("labels_settings", "删除"))
        self.fan.setText(_translate("labels_settings", "反选"))
