# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1066, 647)
        MainWindow.setMinimumSize(QtCore.QSize(600, 400))
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_3.setContentsMargins(3, -1, 3, -1)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setContentsMargins(-1, 0, -1, -1)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.listcon = QtWidgets.QPushButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.listcon.sizePolicy().hasHeightForWidth())
        self.listcon.setSizePolicy(sizePolicy)
        self.listcon.setMinimumSize(QtCore.QSize(25, 25))
        self.listcon.setStyleSheet("QPushButton {\n"
"    background-color: #54687a; /* 默认颜色，浅灰色 */\n"
"    border: 1px solid #259ae9; /* 灰色的边框 */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #54687a; /* 鼠标悬停时的颜色，稍浅的灰色 */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #455364; /* 鼠标点击时的颜色，稍深的灰色 */\n"
"}\n"
"")
        self.listcon.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("resources/op_icon/folder.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.listcon.setIcon(icon)
        self.listcon.setObjectName("listcon")
        self.verticalLayout_8.addWidget(self.listcon)
        self.workcon = QtWidgets.QPushButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.workcon.sizePolicy().hasHeightForWidth())
        self.workcon.setSizePolicy(sizePolicy)
        self.workcon.setMinimumSize(QtCore.QSize(25, 25))
        self.workcon.setStyleSheet("QPushButton {\n"
"    background-color: #54687a; /* 默认颜色，浅灰色 */\n"
"    border: 1px solid #259ae9; /* 灰色的边框 */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #54687a; /* 鼠标悬停时的颜色，稍浅的灰色 */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #455364; /* 鼠标点击时的颜色，稍深的灰色 */\n"
"}\n"
"")
        self.workcon.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("resources/op_icon/workspace.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.workcon.setIcon(icon1)
        self.workcon.setObjectName("workcon")
        self.verticalLayout_8.addWidget(self.workcon)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_8.addItem(spacerItem)
        self.terminalcon = QtWidgets.QPushButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.terminalcon.sizePolicy().hasHeightForWidth())
        self.terminalcon.setSizePolicy(sizePolicy)
        self.terminalcon.setMinimumSize(QtCore.QSize(25, 25))
        self.terminalcon.setStyleSheet("QPushButton {\n"
"    background-color: #54687a; /* 默认颜色，浅灰色 */\n"
"    border: 1px solid #259ae9; /* 灰色的边框 */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #54687a; /* 鼠标悬停时的颜色，稍浅的灰色 */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #455364; /* 鼠标点击时的颜色，稍深的灰色 */\n"
"}\n"
"")
        self.terminalcon.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("resources/op_icon/terminal.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.terminalcon.setIcon(icon2)
        self.terminalcon.setObjectName("terminalcon")
        self.verticalLayout_8.addWidget(self.terminalcon)
        spacerItem1 = QtWidgets.QSpacerItem(20, 60, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_8.addItem(spacerItem1)
        self.verticalLayout_8.setStretch(2, 1)
        self.gridLayout_3.addLayout(self.verticalLayout_8, 0, 0, 1, 1)
        self.horizontalLayout.addWidget(self.groupBox)
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setContentsMargins(-1, -1, -1, 0)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.useSpace = QtWidgets.QWidget(self.centralwidget)
        self.useSpace.setObjectName("useSpace")
        self.gridLayout_16 = QtWidgets.QGridLayout(self.useSpace)
        self.gridLayout_16.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_16.setObjectName("gridLayout_16")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.widget_list = QtWidgets.QWidget(self.useSpace)
        self.widget_list.setObjectName("widget_list")
        self.gridLayout_14 = QtWidgets.QGridLayout(self.widget_list)
        self.gridLayout_14.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_14.setObjectName("gridLayout_14")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout()
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.original = QtWidgets.QWidget(self.widget_list)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(7)
        self.original.setFont(font)
        self.original.setObjectName("original")
        self.gridLayout_12 = QtWidgets.QGridLayout(self.original)
        self.gridLayout_12.setContentsMargins(-1, 6, -1, 6)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setSpacing(2)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.v_d_comboBox = QtWidgets.QComboBox(self.original)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.v_d_comboBox.sizePolicy().hasHeightForWidth())
        self.v_d_comboBox.setSizePolicy(sizePolicy)
        self.v_d_comboBox.setMinimumSize(QtCore.QSize(0, 25))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(9)
        self.v_d_comboBox.setFont(font)
        self.v_d_comboBox.setObjectName("v_d_comboBox")
        self.v_d_comboBox.addItem("")
        self.v_d_comboBox.addItem("")
        self.horizontalLayout_3.addWidget(self.v_d_comboBox)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setContentsMargins(-1, -1, 0, -1)
        self.horizontalLayout_12.setSpacing(2)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.new_file = QtWidgets.QPushButton(self.original)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.new_file.sizePolicy().hasHeightForWidth())
        self.new_file.setSizePolicy(sizePolicy)
        self.new_file.setMinimumSize(QtCore.QSize(15, 15))
        self.new_file.setStyleSheet("QPushButton {\n"
"    background-color: #455364; /* 默认颜色，浅灰色 */\n"
"    border: 1px solid #666666; /* 灰色的边框 */\n"
"    padding: 5px 10px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #54687a; /* 鼠标悬停时的颜色，稍浅的灰色 */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #455364; /* 鼠标点击时的颜色，稍深的灰色 */\n"
"}\n"
"")
        self.new_file.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("resources/op_icon/file.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.new_file.setIcon(icon3)
        self.new_file.setIconSize(QtCore.QSize(15, 15))
        self.new_file.setAutoDefault(False)
        self.new_file.setDefault(False)
        self.new_file.setFlat(False)
        self.new_file.setObjectName("new_file")
        self.horizontalLayout_12.addWidget(self.new_file)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem2)
        self.add_workspace = QtWidgets.QPushButton(self.original)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.add_workspace.sizePolicy().hasHeightForWidth())
        self.add_workspace.setSizePolicy(sizePolicy)
        self.add_workspace.setMinimumSize(QtCore.QSize(15, 15))
        self.add_workspace.setStyleSheet("QPushButton {\n"
"    background-color: #455364; /* 默认颜色，浅灰色 */\n"
"    border: 1px solid #666666; /* 灰色的边框 */\n"
"    padding: 5px 10px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #54687a; /* 鼠标悬停时的颜色，稍浅的灰色 */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #455364; /* 鼠标点击时的颜色，稍深的灰色 */\n"
"}\n"
"")
        self.add_workspace.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("resources/op_icon/add.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.add_workspace.setIcon(icon4)
        self.add_workspace.setIconSize(QtCore.QSize(15, 15))
        self.add_workspace.setObjectName("add_workspace")
        self.horizontalLayout_12.addWidget(self.add_workspace)
        self.rename = QtWidgets.QPushButton(self.original)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rename.sizePolicy().hasHeightForWidth())
        self.rename.setSizePolicy(sizePolicy)
        self.rename.setMinimumSize(QtCore.QSize(15, 15))
        self.rename.setStyleSheet("QPushButton {\n"
"    background-color: #455364; /* 默认颜色，浅灰色 */\n"
"    border: 1px solid #666666; /* 灰色的边框 */\n"
"    padding: 5px 10px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #54687a; /* 鼠标悬停时的颜色，稍浅的灰色 */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #455364; /* 鼠标点击时的颜色，稍深的灰色 */\n"
"}\n"
"")
        self.rename.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("resources/op_icon/rename.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.rename.setIcon(icon5)
        self.rename.setIconSize(QtCore.QSize(15, 15))
        self.rename.setObjectName("rename")
        self.horizontalLayout_12.addWidget(self.rename)
        self.delete_file = QtWidgets.QPushButton(self.original)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.delete_file.sizePolicy().hasHeightForWidth())
        self.delete_file.setSizePolicy(sizePolicy)
        self.delete_file.setMinimumSize(QtCore.QSize(15, 15))
        self.delete_file.setStyleSheet("QPushButton {\n"
"    background-color: #455364; /* 默认颜色，浅灰色 */\n"
"    border: 1px solid #666666; /* 灰色的边框 */\n"
"    padding: 5px 10px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #54687a; /* 鼠标悬停时的颜色，稍浅的灰色 */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #455364; /* 鼠标点击时的颜色，稍深的灰色 */\n"
"}\n"
"")
        self.delete_file.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("resources/op_icon/delete-file.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.delete_file.setIcon(icon6)
        self.delete_file.setIconSize(QtCore.QSize(15, 15))
        self.delete_file.setObjectName("delete_file")
        self.horizontalLayout_12.addWidget(self.delete_file)
        self.verticalLayout.addLayout(self.horizontalLayout_12)
        self.video_tree = QtWidgets.QTreeWidget(self.original)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(9)
        self.video_tree.setFont(font)
        self.video_tree.setStyleSheet("QPushButton {\n"
"    background-color: rgb(255, 255, 255); /* 默认颜色，浅灰色 */\n"
"    border: none;\n"
"    padding: 5px 10px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color:54687a; /* 鼠标悬停时的颜色，稍浅的灰色 */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #606060; /* 鼠标点击时的颜色，稍深的灰色 */\n"
"}\n"
"")
        self.video_tree.setObjectName("video_tree")
        self.video_tree.headerItem().setText(0, "1")
        self.video_tree.header().setVisible(False)
        self.verticalLayout.addWidget(self.video_tree)
        self.verticalLayout.setStretch(0, 1)
        self.verticalLayout.setStretch(2, 20)
        self.gridLayout_12.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.verticalLayout_13.addWidget(self.original)
        self.works = QtWidgets.QWidget(self.widget_list)
        font = QtGui.QFont()
        font.setPointSize(7)
        self.works.setFont(font)
        self.works.setObjectName("works")
        self.gridLayout_13 = QtWidgets.QGridLayout(self.works)
        self.gridLayout_13.setContentsMargins(-1, 6, -1, 0)
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setContentsMargins(-1, -1, 0, -1)
        self.horizontalLayout_15.setSpacing(2)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.clear_workspace = QtWidgets.QPushButton(self.works)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.clear_workspace.sizePolicy().hasHeightForWidth())
        self.clear_workspace.setSizePolicy(sizePolicy)
        self.clear_workspace.setMinimumSize(QtCore.QSize(15, 15))
        self.clear_workspace.setStyleSheet("QPushButton {\n"
"    background-color: #455364; /* 默认颜色，浅灰色 */\n"
"    border: 1px solid #666666; /* 灰色的边框 */\n"
"    padding: 5px 10px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #54687a; /* 鼠标悬停时的颜色，稍浅的灰色 */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #455364; /* 鼠标点击时的颜色，稍深的灰色 */\n"
"}\n"
"")
        self.clear_workspace.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("resources/op_icon/clear.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.clear_workspace.setIcon(icon7)
        self.clear_workspace.setIconSize(QtCore.QSize(15, 15))
        self.clear_workspace.setAutoDefault(False)
        self.clear_workspace.setDefault(False)
        self.clear_workspace.setFlat(False)
        self.clear_workspace.setObjectName("clear_workspace")
        self.horizontalLayout_15.addWidget(self.clear_workspace)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_15.addItem(spacerItem3)
        self.rename_2 = QtWidgets.QPushButton(self.works)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rename_2.sizePolicy().hasHeightForWidth())
        self.rename_2.setSizePolicy(sizePolicy)
        self.rename_2.setMinimumSize(QtCore.QSize(15, 15))
        self.rename_2.setStyleSheet("QPushButton {\n"
"    background-color: #455364; /* 默认颜色，浅灰色 */\n"
"    border: 1px solid #666666; /* 灰色的边框 */\n"
"    padding: 5px 10px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #54687a; /* 鼠标悬停时的颜色，稍浅的灰色 */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #455364; /* 鼠标点击时的颜色，稍深的灰色 */\n"
"}\n"
"")
        self.rename_2.setText("")
        self.rename_2.setIcon(icon5)
        self.rename_2.setIconSize(QtCore.QSize(15, 15))
        self.rename_2.setObjectName("rename_2")
        self.horizontalLayout_15.addWidget(self.rename_2)
        self.delete_file_2 = QtWidgets.QPushButton(self.works)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.delete_file_2.sizePolicy().hasHeightForWidth())
        self.delete_file_2.setSizePolicy(sizePolicy)
        self.delete_file_2.setMinimumSize(QtCore.QSize(15, 15))
        self.delete_file_2.setStyleSheet("QPushButton {\n"
"    background-color: #455364; /* 默认颜色，浅灰色 */\n"
"    border: 1px solid #666666; /* 灰色的边框 */\n"
"    padding: 5px 10px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #54687a; /* 鼠标悬停时的颜色，稍浅的灰色 */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #455364; /* 鼠标点击时的颜色，稍深的灰色 */\n"
"}\n"
"")
        self.delete_file_2.setText("")
        self.delete_file_2.setIcon(icon6)
        self.delete_file_2.setIconSize(QtCore.QSize(15, 15))
        self.delete_file_2.setObjectName("delete_file_2")
        self.horizontalLayout_15.addWidget(self.delete_file_2)
        self.verticalLayout_9.addLayout(self.horizontalLayout_15)
        self.work_list = QtWidgets.QTreeWidget(self.works)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(7)
        self.work_list.setFont(font)
        self.work_list.setObjectName("work_list")
        self.work_list.headerItem().setText(0, "1")
        self.work_list.header().setVisible(False)
        self.verticalLayout_9.addWidget(self.work_list)
        self.gridLayout_13.addLayout(self.verticalLayout_9, 1, 0, 1, 1)
        self.groupBox1 = QtWidgets.QGroupBox(self.works)
        self.groupBox1.setObjectName("groupBox1")
        self.gridLayout_15 = QtWidgets.QGridLayout(self.groupBox1)
        self.gridLayout_15.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_15.setObjectName("gridLayout_15")
        self.label_3 = QtWidgets.QLabel(self.groupBox1)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(7)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.gridLayout_15.addWidget(self.label_3, 0, 0, 1, 1)
        self.gridLayout_13.addWidget(self.groupBox1, 0, 0, 1, 1)
        self.verticalLayout_13.addWidget(self.works)
        self.gridLayout_14.addLayout(self.verticalLayout_13, 0, 0, 1, 1)
        self.horizontalLayout_14.addWidget(self.widget_list)
        self.tabWidget = QtWidgets.QTabWidget(self.useSpace)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.tabWidget.setFont(font)
        self.tabWidget.setObjectName("tabWidget")
        self.ori_video = QtWidgets.QWidget()
        self.ori_video.setObjectName("ori_video")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.ori_video)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.video_widget = QtWidgets.QWidget(self.ori_video)
        self.video_widget.setObjectName("video_widget")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.video_widget)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.player = QtWidgets.QLabel(self.video_widget)
        self.player.setStyleSheet("\n"
"        background: rgb(0, 0, 0);")
        self.player.setText("")
        self.player.setObjectName("player")
        self.verticalLayout_2.addWidget(self.player)
        self.camera = QtWidgets.QLabel(self.video_widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.camera.sizePolicy().hasHeightForWidth())
        self.camera.setSizePolicy(sizePolicy)
        self.camera.setStyleSheet("\n"
"        background: rgb(0, 0, 0);")
        self.camera.setText("")
        self.camera.setObjectName("camera")
        self.verticalLayout_2.addWidget(self.camera)
        spacerItem4 = QtWidgets.QSpacerItem(20, 5, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem4)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setSpacing(0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.prev = QtWidgets.QPushButton(self.video_widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.prev.sizePolicy().hasHeightForWidth())
        self.prev.setSizePolicy(sizePolicy)
        self.prev.setMinimumSize(QtCore.QSize(25, 25))
        self.prev.setStyleSheet("QPushButton {\n"
"    background-color: #455364; /* 默认颜色，浅灰色 */\n"
"    border: 1px solid #666666; /* 灰色的边框 */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #54687a; /* 鼠标悬停时的颜色，稍浅的灰色 */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #455364; /* 鼠标点击时的颜色，稍深的灰色 */\n"
"}\n"
"")
        self.prev.setText("")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap("resources/op_icon/prev.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.prev.setIcon(icon8)
        self.prev.setObjectName("prev")
        self.horizontalLayout_6.addWidget(self.prev)
        spacerItem5 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem5)
        self.play_pause = QtWidgets.QPushButton(self.video_widget)
        self.play_pause.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.play_pause.sizePolicy().hasHeightForWidth())
        self.play_pause.setSizePolicy(sizePolicy)
        self.play_pause.setMinimumSize(QtCore.QSize(25, 25))
        self.play_pause.setStyleSheet("QPushButton {\n"
"    background-color: #455364; /* 默认颜色，浅灰色 */\n"
"    border: 1px solid #666666; /* 灰色的边框 */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #54687a; /* 鼠标悬停时的颜色，稍浅的灰色 */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #455364; /* 鼠标点击时的颜色，稍深的灰色 */\n"
"}\n"
"")
        self.play_pause.setText("")
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap("resources/play_ico.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.play_pause.setIcon(icon9)
        self.play_pause.setObjectName("play_pause")
        self.horizontalLayout_6.addWidget(self.play_pause)
        spacerItem6 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem6)
        self.next = QtWidgets.QPushButton(self.video_widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.next.sizePolicy().hasHeightForWidth())
        self.next.setSizePolicy(sizePolicy)
        self.next.setMinimumSize(QtCore.QSize(25, 25))
        self.next.setStyleSheet("QPushButton {\n"
"    background-color: #455364; /* 默认颜色，浅灰色 */\n"
"    border: 1px solid #666666; /* 灰色的边框 */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #54687a; /* 鼠标悬停时的颜色，稍浅的灰色 */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #455364; /* 鼠标点击时的颜色，稍深的灰色 */\n"
"}\n"
"")
        self.next.setText("")
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap("resources/op_icon/next.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.next.setIcon(icon10)
        self.next.setObjectName("next")
        self.horizontalLayout_6.addWidget(self.next)
        spacerItem7 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem7)
        self.video_slider = QtWidgets.QSlider(self.video_widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.video_slider.sizePolicy().hasHeightForWidth())
        self.video_slider.setSizePolicy(sizePolicy)
        self.video_slider.setStyleSheet("")
        self.video_slider.setOrientation(QtCore.Qt.Horizontal)
        self.video_slider.setObjectName("video_slider")
        self.horizontalLayout_6.addWidget(self.video_slider)
        self.video_time = QtWidgets.QLabel(self.video_widget)
        font = QtGui.QFont()
        font.setFamily("小米兰亭")
        font.setPointSize(12)
        self.video_time.setFont(font)
        self.video_time.setObjectName("video_time")
        self.horizontalLayout_6.addWidget(self.video_time)
        self.label = QtWidgets.QLabel(self.video_widget)
        font = QtGui.QFont()
        font.setFamily("小米兰亭")
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout_6.addWidget(self.label)
        self.video_time_all = QtWidgets.QLabel(self.video_widget)
        font = QtGui.QFont()
        font.setFamily("小米兰亭")
        font.setPointSize(12)
        self.video_time_all.setFont(font)
        self.video_time_all.setObjectName("video_time_all")
        self.horizontalLayout_6.addWidget(self.video_time_all)
        spacerItem8 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem8)
        self.speed = QtWidgets.QComboBox(self.video_widget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.speed.setFont(font)
        self.speed.setObjectName("speed")
        self.speed.addItem("")
        self.speed.addItem("")
        self.speed.addItem("")
        self.speed.addItem("")
        self.horizontalLayout_6.addWidget(self.speed)
        self.horizontalLayout_6.setStretch(6, 10)
        self.verticalLayout_2.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setSpacing(0)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        spacerItem9 = QtWidgets.QSpacerItem(105, 0, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem9)
        self.cut_slider = RangeSlider(self.video_widget)
        self.cut_slider.setStyleSheet("QSlider::handle:horizontal:hover {\n"
"        width:  50px; \n"
"        height: 50px; \n"
"        margin-top: -20px; \n"
"        margin-left: 0px; \n"
"        margin-bottom: -20px; \n"
"        margin-right: 0px; \n"
"         border-image:url(:/res/images/setting_slider_handle_hover.png);\n"
"}\n"
"QSlider::sub-page:horizontal:disabled {\n"
"        background: #BB345F;\n"
"}\n"
"QSlider::add-page:horizontal:disabled {\n"
"        background: #1ADEFF;\n"
"}\n"
"QSlider::handle:horizontal:disabled {\n"
"        background: #EEDDFF;\n"
"")
        self.cut_slider.setOrientation(QtCore.Qt.Horizontal)
        self.cut_slider.setObjectName("cut_slider")
        self.horizontalLayout_13.addWidget(self.cut_slider)
        self.cut_time = QtWidgets.QLabel(self.video_widget)
        font = QtGui.QFont()
        font.setFamily("小米兰亭")
        font.setPointSize(12)
        self.cut_time.setFont(font)
        self.cut_time.setObjectName("cut_time")
        self.horizontalLayout_13.addWidget(self.cut_time)
        self.label_2 = QtWidgets.QLabel(self.video_widget)
        font = QtGui.QFont()
        font.setFamily("小米兰亭")
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_13.addWidget(self.label_2)
        self.cut_time_all = QtWidgets.QLabel(self.video_widget)
        font = QtGui.QFont()
        font.setFamily("小米兰亭")
        font.setPointSize(12)
        self.cut_time_all.setFont(font)
        self.cut_time_all.setObjectName("cut_time_all")
        self.horizontalLayout_13.addWidget(self.cut_time_all)
        spacerItem10 = QtWidgets.QSpacerItem(66, 0, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem10)
        self.verticalLayout_2.addLayout(self.horizontalLayout_13)
        self.verticalLayout_2.setStretch(0, 9)
        self.verticalLayout_2.setStretch(1, 9)
        self.verticalLayout_2.setStretch(3, 1)
        self.gridLayout_4.addLayout(self.verticalLayout_2, 0, 0, 1, 1)
        self.horizontalLayout_5.addWidget(self.video_widget)
        self.video_label_widget = QtWidgets.QWidget(self.ori_video)
        self.video_label_widget.setObjectName("video_label_widget")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.video_label_widget)
        self.gridLayout_6.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.video_info = QtWidgets.QTextBrowser(self.video_label_widget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(9)
        self.video_info.setFont(font)
        self.video_info.setObjectName("video_info")
        self.verticalLayout_3.addWidget(self.video_info)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.video_label = QtWidgets.QLabel(self.video_label_widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.video_label.sizePolicy().hasHeightForWidth())
        self.video_label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(9)
        self.video_label.setFont(font)
        self.video_label.setObjectName("video_label")
        self.horizontalLayout_4.addWidget(self.video_label)
        self.save_label = QtWidgets.QPushButton(self.video_label_widget)
        self.save_label.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.save_label.sizePolicy().hasHeightForWidth())
        self.save_label.setSizePolicy(sizePolicy)
        self.save_label.setMouseTracking(False)
        self.save_label.setStyleSheet("QPushButton {\n"
"    background-color: #455364; /* 默认颜色，浅灰色 */\n"
"    border: 1px solid #666666; /* 灰色的边框 */\n"
"    padding: 5px 10px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #54687a; /* 鼠标悬停时的颜色，稍浅的灰色 */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #455364; /* 鼠标点击时的颜色，稍深的灰色 */\n"
"}\n"
"")
        self.save_label.setText("")
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap("resources/op_icon/save.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.save_label.setIcon(icon11)
        self.save_label.setAutoRepeat(False)
        self.save_label.setAutoDefault(False)
        self.save_label.setDefault(False)
        self.save_label.setFlat(False)
        self.save_label.setObjectName("save_label")
        self.horizontalLayout_4.addWidget(self.save_label)
        self.horizontalLayout_4.setStretch(0, 4)
        self.horizontalLayout_4.setStretch(1, 1)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.video_label_edit = QtWidgets.QTextEdit(self.video_label_widget)
        self.video_label_edit.setEnabled(False)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(9)
        self.video_label_edit.setFont(font)
        self.video_label_edit.setStatusTip("")
        self.video_label_edit.setAccessibleDescription("")
        self.video_label_edit.setObjectName("video_label_edit")
        self.verticalLayout_3.addWidget(self.video_label_edit)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.cut_mode = QtWidgets.QPushButton(self.video_label_widget)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(69, 83, 100))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(229, 229, 229))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(69, 83, 100))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(69, 83, 100))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(69, 83, 100))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(229, 229, 229))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(69, 83, 100))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(69, 83, 100))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(69, 83, 100))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(69, 83, 100))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(69, 83, 100))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.cut_mode.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(9)
        self.cut_mode.setFont(font)
        self.cut_mode.setStyleSheet("QPushButton {\n"
"    background-color: #455364; /* 默认颜色，浅灰色 */\n"
"    border: 1px solid #666666; /* 灰色的边框 */\n"
"    padding: 5px 10px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #54687a; /* 鼠标悬停时的颜色，稍浅的灰色 */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #455364; /* 鼠标点击时的颜色，稍深的灰色 */\n"
"}\n"
"")
        self.cut_mode.setObjectName("cut_mode")
        self.horizontalLayout_2.addWidget(self.cut_mode)
        self.save_cut = QtWidgets.QPushButton(self.video_label_widget)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(69, 83, 100))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(229, 229, 229))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(69, 83, 100))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(69, 83, 100))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(69, 83, 100))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(229, 229, 229))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(69, 83, 100))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(69, 83, 100))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(69, 83, 100))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(69, 83, 100))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(69, 83, 100))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.save_cut.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(9)
        self.save_cut.setFont(font)
        self.save_cut.setStyleSheet("QPushButton {\n"
"    background-color: #455364; /* 默认颜色，浅灰色 */\n"
"    border: 1px solid #666666; /* 灰色的边框 */\n"
"    padding: 5px 10px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #54687a; /* 鼠标悬停时的颜色，稍浅的灰色 */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #455364; /* 鼠标点击时的颜色，稍深的灰色 */\n"
"}\n"
"")
        self.save_cut.setObjectName("save_cut")
        self.horizontalLayout_2.addWidget(self.save_cut)
        self.exit_mode = QtWidgets.QPushButton(self.video_label_widget)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(69, 83, 100))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(229, 229, 229))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(69, 83, 100))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(69, 83, 100))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(69, 83, 100))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(229, 229, 229))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(69, 83, 100))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(69, 83, 100))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(69, 83, 100))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(69, 83, 100))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(69, 83, 100))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.exit_mode.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(9)
        self.exit_mode.setFont(font)
        self.exit_mode.setStyleSheet("QPushButton {\n"
"    background-color: #455364; /* 默认颜色，浅灰色 */\n"
"    border: 1px solid #666666; /* 灰色的边框 */\n"
"    padding: 5px 10px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #54687a; /* 鼠标悬停时的颜色，稍浅的灰色 */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #455364; /* 鼠标点击时的颜色，稍深的灰色 */\n"
"}\n"
"")
        self.exit_mode.setObjectName("exit_mode")
        self.horizontalLayout_2.addWidget(self.exit_mode)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.verticalLayout_3.setStretch(0, 5)
        self.verticalLayout_3.setStretch(2, 5)
        self.verticalLayout_3.setStretch(3, 1)
        self.gridLayout_6.addLayout(self.verticalLayout_3, 0, 0, 1, 1)
        self.horizontalLayout_5.addWidget(self.video_label_widget)
        self.horizontalLayout_5.setStretch(0, 5)
        self.horizontalLayout_5.setStretch(1, 2)
        self.gridLayout_2.addLayout(self.horizontalLayout_5, 0, 0, 1, 1)
        self.tabWidget.addTab(self.ori_video, "")
        self.act_identify = QtWidgets.QWidget()
        self.act_identify.setObjectName("act_identify")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.act_identify)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.video_widget_2 = QtWidgets.QWidget(self.act_identify)
        self.video_widget_2.setObjectName("video_widget_2")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.video_widget_2)
        self.gridLayout_7.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.camera_2 = QtWidgets.QLabel(self.video_widget_2)
        self.camera_2.setStyleSheet("\n"
"        background: rgb(0, 0, 0);")
        self.camera_2.setText("")
        self.camera_2.setObjectName("camera_2")
        self.verticalLayout_4.addWidget(self.camera_2)
        self.player_2 = QVideoWidget(self.video_widget_2)
        self.player_2.setStyleSheet("\n"
"        background: rgb(0, 0, 0);")
        self.player_2.setObjectName("player_2")
        self.verticalLayout_4.addWidget(self.player_2)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.video_slider_2 = QtWidgets.QSlider(self.video_widget_2)
        self.video_slider_2.setStyleSheet("")
        self.video_slider_2.setOrientation(QtCore.Qt.Horizontal)
        self.video_slider_2.setObjectName("video_slider_2")
        self.horizontalLayout_9.addWidget(self.video_slider_2)
        self.video_time_2 = QtWidgets.QLabel(self.video_widget_2)
        self.video_time_2.setObjectName("video_time_2")
        self.horizontalLayout_9.addWidget(self.video_time_2)
        self.horizontalLayout_9.setStretch(0, 10)
        self.horizontalLayout_9.setStretch(1, 1)
        self.horizontalLayout_8.addLayout(self.horizontalLayout_9)
        self.verticalLayout_4.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.stop_identify = QtWidgets.QPushButton(self.video_widget_2)
        self.stop_identify.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stop_identify.sizePolicy().hasHeightForWidth())
        self.stop_identify.setSizePolicy(sizePolicy)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(69, 83, 100))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(69, 83, 100))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(69, 83, 100))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(69, 83, 100))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(69, 83, 100))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(69, 83, 100))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(69, 83, 100))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(69, 83, 100))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(69, 83, 100))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.stop_identify.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(9)
        self.stop_identify.setFont(font)
        self.stop_identify.setStyleSheet("QPushButton {\n"
"    background-color: #455364; /* 默认颜色，浅灰色 */\n"
"    border: 1px solid #666666; /* 灰色的边框 */\n"
"    padding: 5px 10px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #54687a; /* 鼠标悬停时的颜色，稍浅的灰色 */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #455364; /* 鼠标点击时的颜色，稍深的灰色 */\n"
"}\n"
"")
        self.stop_identify.setObjectName("stop_identify")
        self.horizontalLayout_11.addWidget(self.stop_identify)
        self.start_identify = QtWidgets.QPushButton(self.video_widget_2)
        self.start_identify.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.start_identify.sizePolicy().hasHeightForWidth())
        self.start_identify.setSizePolicy(sizePolicy)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(69, 83, 100))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(229, 229, 229))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(69, 83, 100))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(69, 83, 100))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(105, 105, 105))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(69, 83, 100))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(229, 229, 229))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(69, 83, 100))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(69, 83, 100))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(105, 105, 105))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(69, 83, 100))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(69, 83, 100))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(69, 83, 100))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(105, 105, 105))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        self.start_identify.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(9)
        self.start_identify.setFont(font)
        self.start_identify.setStyleSheet("QPushButton {\n"
"    background-color: #455364; /* 默认颜色，浅灰色 */\n"
"    border: 1px solid #666666; /* 灰色的边框 */\n"
"    padding: 5px 10px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #54687a; /* 鼠标悬停时的颜色，稍浅的灰色 */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #455364; /* 鼠标点击时的颜色，稍深的灰色 */\n"
"}\n"
"")
        self.start_identify.setObjectName("start_identify")
        self.horizontalLayout_11.addWidget(self.start_identify)
        self.verticalLayout_4.addLayout(self.horizontalLayout_11)
        self.verticalLayout_4.setStretch(0, 9)
        self.verticalLayout_4.setStretch(2, 1)
        self.gridLayout_7.addLayout(self.verticalLayout_4, 0, 0, 1, 1)
        self.horizontalLayout_7.addWidget(self.video_widget_2)
        self.video_label_widget_2 = QtWidgets.QWidget(self.act_identify)
        self.video_label_widget_2.setObjectName("video_label_widget_2")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.video_label_widget_2)
        self.gridLayout_8.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.action_list = QtWidgets.QListWidget(self.video_label_widget_2)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(9)
        self.action_list.setFont(font)
        self.action_list.setObjectName("action_list")
        self.verticalLayout_5.addWidget(self.action_list)
        self.result_tab = QtWidgets.QTabWidget(self.video_label_widget_2)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(9)
        self.result_tab.setFont(font)
        self.result_tab.setObjectName("result_tab")
        self.search_tab = QtWidgets.QWidget()
        self.search_tab.setObjectName("search_tab")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.search_tab)
        self.gridLayout_5.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setSpacing(6)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.item_search = QtWidgets.QLineEdit(self.search_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.item_search.sizePolicy().hasHeightForWidth())
        self.item_search.setSizePolicy(sizePolicy)
        self.item_search.setObjectName("item_search")
        self.horizontalLayout_10.addWidget(self.item_search)
        self.item_search_button = QtWidgets.QPushButton(self.search_tab)
        self.item_search_button.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.item_search_button.sizePolicy().hasHeightForWidth())
        self.item_search_button.setSizePolicy(sizePolicy)
        self.item_search_button.setMouseTracking(False)
        self.item_search_button.setStyleSheet("QPushButton {\n"
"    background-color: #455364; /* 默认颜色，浅灰色 */\n"
"    border: 1px solid #666666; /* 灰色的边框 */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #54687a; /* 鼠标悬停时的颜色，稍浅的灰色 */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #455364; /* 鼠标点击时的颜色，稍深的灰色 */\n"
"}\n"
"")
        self.item_search_button.setText("")
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap("resources/op_icon/search.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.item_search_button.setIcon(icon12)
        self.item_search_button.setAutoRepeat(False)
        self.item_search_button.setAutoDefault(False)
        self.item_search_button.setDefault(False)
        self.item_search_button.setFlat(False)
        self.item_search_button.setObjectName("item_search_button")
        self.horizontalLayout_10.addWidget(self.item_search_button)
        self.horizontalLayout_10.setStretch(1, 1)
        self.gridLayout_5.addLayout(self.horizontalLayout_10, 0, 0, 1, 1)
        self.search_result = QtWidgets.QListWidget(self.search_tab)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(9)
        self.search_result.setFont(font)
        self.search_result.setObjectName("search_result")
        self.gridLayout_5.addWidget(self.search_result, 1, 0, 1, 1)
        self.result_tab.addTab(self.search_tab, "")
        self.plot_tab = QtWidgets.QWidget()
        self.plot_tab.setObjectName("plot_tab")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.plot_tab)
        self.gridLayout_10.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.gridLayout_10.addLayout(self.verticalLayout_6, 0, 0, 1, 1)
        self.result_tab.addTab(self.plot_tab, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.tab_3)
        self.gridLayout_11.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.gridLayout_11.addLayout(self.verticalLayout_7, 0, 0, 1, 1)
        self.result_tab.addTab(self.tab_3, "")
        self.verticalLayout_5.addWidget(self.result_tab)
        self.verticalLayout_5.setStretch(0, 4)
        self.verticalLayout_5.setStretch(1, 5)
        self.gridLayout_8.addLayout(self.verticalLayout_5, 0, 0, 1, 1)
        self.horizontalLayout_7.addWidget(self.video_label_widget_2)
        self.horizontalLayout_7.setStretch(0, 5)
        self.horizontalLayout_7.setStretch(1, 2)
        self.gridLayout_9.addLayout(self.horizontalLayout_7, 0, 0, 1, 1)
        self.tabWidget.addTab(self.act_identify, "")
        self.horizontalLayout_14.addWidget(self.tabWidget)
        self.horizontalLayout_14.setStretch(0, 1)
        self.horizontalLayout_14.setStretch(1, 5)
        self.gridLayout_16.addLayout(self.horizontalLayout_14, 0, 0, 1, 1)
        self.verticalLayout_10.addWidget(self.useSpace)
        self.controlWidget = QtWidgets.QGroupBox(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(6)
        self.controlWidget.setFont(font)
        self.controlWidget.setObjectName("controlWidget")
        self.gridLayout_17 = QtWidgets.QGridLayout(self.controlWidget)
        self.gridLayout_17.setContentsMargins(0, 3, 0, 0)
        self.gridLayout_17.setHorizontalSpacing(6)
        self.gridLayout_17.setVerticalSpacing(0)
        self.gridLayout_17.setObjectName("gridLayout_17")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout()
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.terminal = QtWidgets.QTextEdit(self.controlWidget)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.PlaceholderText, brush)
        self.terminal.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(7)
        self.terminal.setFont(font)
        self.terminal.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.terminal.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.terminal.setAutoFillBackground(False)
        self.terminal.setReadOnly(True)
        self.terminal.setObjectName("terminal")
        self.verticalLayout_11.addWidget(self.terminal)
        self.gridLayout_17.addLayout(self.verticalLayout_11, 2, 0, 1, 1)
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.gridLayout_17.addLayout(self.horizontalLayout_16, 0, 0, 1, 1)
        self.verticalLayout_10.addWidget(self.controlWidget)
        self.verticalLayout_10.setStretch(0, 10)
        self.verticalLayout_10.setStretch(1, 1)
        self.horizontalLayout.addLayout(self.verticalLayout_10)
        self.horizontalLayout.setStretch(1, 1)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1066, 26))
        self.menubar.setObjectName("menubar")
        self.system_set = QtWidgets.QMenu(self.menubar)
        self.system_set.setObjectName("system_set")
        self.device_manager = QtWidgets.QMenu(self.menubar)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.device_manager.setFont(font)
        self.device_manager.setObjectName("device_manager")
        self.model_manager = QtWidgets.QMenu(self.menubar)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.model_manager.setFont(font)
        self.model_manager.setObjectName("model_manager")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.video_select = QtWidgets.QAction(MainWindow)
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap("resources/file.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.video_select.setIcon(icon13)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.video_select.setFont(font)
        self.video_select.setObjectName("video_select")
        self.action = QtWidgets.QAction(MainWindow)
        self.action.setObjectName("action")
        self.video_path = QtWidgets.QAction(MainWindow)
        self.video_path.setObjectName("video_path")
        self.save_path = QtWidgets.QAction(MainWindow)
        self.save_path.setObjectName("save_path")
        self.model_view = QtWidgets.QAction(MainWindow)
        self.model_view.setObjectName("model_view")
        self.action_6 = QtWidgets.QAction(MainWindow)
        self.action_6.setObjectName("action_6")
        self.quit = QtWidgets.QAction(MainWindow)
        self.quit.setObjectName("quit")
        self.action_sets = QtWidgets.QAction(MainWindow)
        self.action_sets.setObjectName("action_sets")
        self.Use_Information = QtWidgets.QAction(MainWindow)
        self.Use_Information.setObjectName("Use_Information")
        self.Version_Information = QtWidgets.QAction(MainWindow)
        self.Version_Information.setObjectName("Version_Information")
        self.action_2 = QtWidgets.QAction(MainWindow)
        self.action_2.setObjectName("action_2")
        self.action_3 = QtWidgets.QAction(MainWindow)
        self.action_3.setObjectName("action_3")
        self.action_4 = QtWidgets.QAction(MainWindow)
        self.action_4.setObjectName("action_4")
        self.action_5 = QtWidgets.QAction(MainWindow)
        self.action_5.setObjectName("action_5")
        self.system_set.addAction(self.video_select)
        self.system_set.addSeparator()
        self.system_set.addAction(self.video_path)
        self.system_set.addAction(self.save_path)
        self.system_set.addSeparator()
        self.system_set.addAction(self.action_6)
        self.system_set.addSeparator()
        self.system_set.addAction(self.quit)
        self.device_manager.addAction(self.action)
        self.device_manager.addAction(self.action_2)
        self.device_manager.addAction(self.action_3)
        self.device_manager.addAction(self.action_4)
        self.model_manager.addAction(self.model_view)
        self.model_manager.addAction(self.action_sets)
        self.menu.addAction(self.Use_Information)
        self.menu.addAction(self.Version_Information)
        self.menubar.addAction(self.system_set.menuAction())
        self.menubar.addAction(self.device_manager.menuAction())
        self.menubar.addAction(self.model_manager.menuAction())
        self.menubar.addAction(self.menu.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.speed.setCurrentIndex(1)
        self.result_tab.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.listcon.setToolTip(_translate("MainWindow", "原始列表"))
        self.workcon.setToolTip(_translate("MainWindow", "工作区"))
        self.terminalcon.setToolTip(_translate("MainWindow", "终端"))
        self.v_d_comboBox.setItemText(0, _translate("MainWindow", "视频列表"))
        self.v_d_comboBox.setItemText(1, _translate("MainWindow", "设备列表"))
        self.new_file.setToolTip(_translate("MainWindow", "刷新列表"))
        self.add_workspace.setToolTip(_translate("MainWindow", "加入工作区"))
        self.rename.setToolTip(_translate("MainWindow", "重命名"))
        self.delete_file.setToolTip(_translate("MainWindow", "删除文件"))
        self.video_tree.setSortingEnabled(True)
        self.clear_workspace.setToolTip(_translate("MainWindow", "清空工作区"))
        self.rename_2.setToolTip(_translate("MainWindow", "重命名"))
        self.delete_file_2.setToolTip(_translate("MainWindow", "删除文件"))
        self.work_list.setSortingEnabled(True)
        self.label_3.setText(_translate("MainWindow", "工作区"))
        self.video_time.setText(_translate("MainWindow", "--:--"))
        self.label.setText(_translate("MainWindow", "/"))
        self.video_time_all.setText(_translate("MainWindow", "--:--"))
        self.speed.setItemText(0, _translate("MainWindow", "0.5x"))
        self.speed.setItemText(1, _translate("MainWindow", "1.0x"))
        self.speed.setItemText(2, _translate("MainWindow", "2.0x"))
        self.speed.setItemText(3, _translate("MainWindow", "3.0x"))
        self.cut_time.setText(_translate("MainWindow", "--:--"))
        self.label_2.setText(_translate("MainWindow", "/"))
        self.cut_time_all.setText(_translate("MainWindow", "--:--"))
        self.video_label.setText(_translate("MainWindow", "备注"))
        self.video_label_edit.setPlaceholderText(_translate("MainWindow", "在这里输入备注..."))
        self.cut_mode.setText(_translate("MainWindow", "剪辑模式"))
        self.save_cut.setText(_translate("MainWindow", "保存视频"))
        self.exit_mode.setText(_translate("MainWindow", "退出剪辑"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.ori_video), _translate("MainWindow", " 原始/实时视频 "))
        self.video_time_2.setText(_translate("MainWindow", "--:--"))
        self.stop_identify.setText(_translate("MainWindow", "终止识别"))
        self.start_identify.setText(_translate("MainWindow", "启动识别"))
        self.result_tab.setTabText(self.result_tab.indexOf(self.search_tab), _translate("MainWindow", "搜索"))
        self.result_tab.setTabText(self.result_tab.indexOf(self.plot_tab), _translate("MainWindow", "折线图"))
        self.result_tab.setTabText(self.result_tab.indexOf(self.tab_3), _translate("MainWindow", "统计图"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.act_identify), _translate("MainWindow", " 行为识别 "))
        self.controlWidget.setTitle(_translate("MainWindow", "终端"))
        self.terminal.setMarkdown(_translate("MainWindow", "Motion Monitor X -\n"
"\n"
""))
        self.system_set.setTitle(_translate("MainWindow", "系统设置"))
        self.device_manager.setTitle(_translate("MainWindow", "设备管理"))
        self.model_manager.setTitle(_translate("MainWindow", "模型设置"))
        self.menu.setTitle(_translate("MainWindow", " 关于 "))
        self.video_select.setText(_translate("MainWindow", "视频目录选择"))
        self.action.setText(_translate("MainWindow", "增加设备"))
        self.video_path.setText(_translate("MainWindow", "默认视频目录"))
        self.save_path.setText(_translate("MainWindow", "默认保存路径"))
        self.model_view.setText(_translate("MainWindow", "模型查看"))
        self.action_6.setText(_translate("MainWindow", "保存"))
        self.quit.setText(_translate("MainWindow", "退出"))
        self.action_sets.setText(_translate("MainWindow", "标签集设置"))
        self.Use_Information.setText(_translate("MainWindow", "使用信息"))
        self.Version_Information.setText(_translate("MainWindow", "版本信息"))
        self.action_2.setText(_translate("MainWindow", "删除设备"))
        self.action_3.setText(_translate("MainWindow", "禁用设备"))
        self.action_4.setText(_translate("MainWindow", "设备参数"))
        self.action_5.setText(_translate("MainWindow", "警告模式设置"))
from PyQt5.QtMultimediaWidgets import QVideoWidget
from range_slider import RangeSlider
