# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'model_settings_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_model_settings(object):
    def setupUi(self, model_settings):
        model_settings.setObjectName("model_settings")
        model_settings.resize(600, 400)
        self.gridLayout = QtWidgets.QGridLayout(model_settings)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout.setSpacing(5)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(model_settings)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(model_settings)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.label_3 = QtWidgets.QLabel(model_settings)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_2.addWidget(self.label_3)
        self.label_4 = QtWidgets.QLabel(model_settings)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_2.addWidget(self.label_4)
        self.label_7 = QtWidgets.QLabel(model_settings)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.label_7.setFont(font)
        self.label_7.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_2.addWidget(self.label_7)
        self.label_8 = QtWidgets.QLabel(model_settings)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_8.sizePolicy().hasHeightForWidth())
        self.label_8.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_2.addWidget(self.label_8)
        self.label_9 = QtWidgets.QLabel(model_settings)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_9.sizePolicy().hasHeightForWidth())
        self.label_9.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.verticalLayout_2.addWidget(self.label_9)
        self.label_10 = QtWidgets.QLabel(model_settings)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_10.sizePolicy().hasHeightForWidth())
        self.label_10.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.verticalLayout_2.addWidget(self.label_10)
        self.verticalLayout_2.setStretch(0, 1)
        self.verticalLayout_2.setStretch(1, 1)
        self.verticalLayout_2.setStretch(2, 1)
        self.verticalLayout_2.setStretch(3, 1)
        self.verticalLayout_2.setStretch(4, 1)
        self.verticalLayout_2.setStretch(5, 1)
        self.verticalLayout_2.setStretch(6, 1)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.save_address_edit = QtWidgets.QLineEdit(model_settings)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.save_address_edit.setFont(font)
        self.save_address_edit.setStyleSheet("border-width:1;border-style:outset;border-color:gray;")
        self.save_address_edit.setReadOnly(True)
        self.save_address_edit.setObjectName("save_address_edit")
        self.verticalLayout_3.addWidget(self.save_address_edit)
        self.pt_edit = QtWidgets.QLineEdit(model_settings)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.pt_edit.setFont(font)
        self.pt_edit.setStyleSheet("border-width:1;border-style:outset;border-color:gray;")
        self.pt_edit.setReadOnly(True)
        self.pt_edit.setObjectName("pt_edit")
        self.verticalLayout_3.addWidget(self.pt_edit)
        self.model_combox = QtWidgets.QComboBox(model_settings)
        self.model_combox.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.model_combox.sizePolicy().hasHeightForWidth())
        self.model_combox.setSizePolicy(sizePolicy)
        self.model_combox.setMinimumSize(QtCore.QSize(0, 24))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.model_combox.setFont(font)
        self.model_combox.setObjectName("model_combox")
        self.model_combox.addItem("")
        self.model_combox.addItem("")
        self.verticalLayout_3.addWidget(self.model_combox)
        self.label_combox = QtWidgets.QComboBox(model_settings)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_combox.sizePolicy().hasHeightForWidth())
        self.label_combox.setSizePolicy(sizePolicy)
        self.label_combox.setMinimumSize(QtCore.QSize(0, 24))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.label_combox.setFont(font)
        self.label_combox.setStyleSheet("")
        self.label_combox.setObjectName("label_combox")
        self.verticalLayout_3.addWidget(self.label_combox)
        self.max_size_comboBox = QtWidgets.QComboBox(model_settings)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.max_size_comboBox.sizePolicy().hasHeightForWidth())
        self.max_size_comboBox.setSizePolicy(sizePolicy)
        self.max_size_comboBox.setMinimumSize(QtCore.QSize(0, 24))
        self.max_size_comboBox.setObjectName("max_size_comboBox")
        self.max_size_comboBox.addItem("")
        self.max_size_comboBox.addItem("")
        self.max_size_comboBox.addItem("")
        self.max_size_comboBox.addItem("")
        self.max_size_comboBox.addItem("")
        self.verticalLayout_3.addWidget(self.max_size_comboBox)
        self.conf_doubleSpinBox = QtWidgets.QDoubleSpinBox(model_settings)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.conf_doubleSpinBox.sizePolicy().hasHeightForWidth())
        self.conf_doubleSpinBox.setSizePolicy(sizePolicy)
        self.conf_doubleSpinBox.setMinimumSize(QtCore.QSize(0, 24))
        self.conf_doubleSpinBox.setMaximum(1.0)
        self.conf_doubleSpinBox.setSingleStep(0.01)
        self.conf_doubleSpinBox.setProperty("value", 0.4)
        self.conf_doubleSpinBox.setObjectName("conf_doubleSpinBox")
        self.verticalLayout_3.addWidget(self.conf_doubleSpinBox)
        self.iou_doubleSpinBox = QtWidgets.QDoubleSpinBox(model_settings)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.iou_doubleSpinBox.sizePolicy().hasHeightForWidth())
        self.iou_doubleSpinBox.setSizePolicy(sizePolicy)
        self.iou_doubleSpinBox.setMinimumSize(QtCore.QSize(0, 24))
        self.iou_doubleSpinBox.setMaximum(1.0)
        self.iou_doubleSpinBox.setSingleStep(0.01)
        self.iou_doubleSpinBox.setStepType(QtWidgets.QAbstractSpinBox.AdaptiveDecimalStepType)
        self.iou_doubleSpinBox.setProperty("value", 0.4)
        self.iou_doubleSpinBox.setObjectName("iou_doubleSpinBox")
        self.verticalLayout_3.addWidget(self.iou_doubleSpinBox)
        self.line_thickness = QtWidgets.QSpinBox(model_settings)
        self.line_thickness.setMinimum(1)
        self.line_thickness.setMaximum(4)
        self.line_thickness.setObjectName("line_thickness")
        self.verticalLayout_3.addWidget(self.line_thickness)
        self.verticalLayout_3.setStretch(0, 1)
        self.verticalLayout_3.setStretch(1, 1)
        self.verticalLayout_3.setStretch(2, 1)
        self.verticalLayout_3.setStretch(3, 1)
        self.verticalLayout_3.setStretch(4, 1)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.save_address_button = QtWidgets.QPushButton(model_settings)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.save_address_button.sizePolicy().hasHeightForWidth())
        self.save_address_button.setSizePolicy(sizePolicy)
        self.save_address_button.setMinimumSize(QtCore.QSize(25, 0))
        self.save_address_button.setSizeIncrement(QtCore.QSize(25, 0))
        self.save_address_button.setStyleSheet("QPushButton {\n"
"    background-color: #455364; /* 默认颜色，浅灰色 */\n"
"    border: 1px solid #666666; /* 灰色的边框 */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #54687a; /* 鼠标悬停时的颜色，稍浅的灰色 */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #455364; /* 鼠标点击时的颜色，稍深的灰色 */\n"
"}\n"
"")
        self.save_address_button.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("resources/op_icon/edit.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.save_address_button.setIcon(icon)
        self.save_address_button.setObjectName("save_address_button")
        self.verticalLayout_4.addWidget(self.save_address_button)
        self.pt_select_button = QtWidgets.QPushButton(model_settings)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pt_select_button.sizePolicy().hasHeightForWidth())
        self.pt_select_button.setSizePolicy(sizePolicy)
        self.pt_select_button.setMinimumSize(QtCore.QSize(25, 0))
        self.pt_select_button.setStyleSheet("QPushButton {\n"
"    background-color: #455364; /* 默认颜色，浅灰色 */\n"
"    border: 1px solid #666666; /* 灰色的边框 */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #54687a; /* 鼠标悬停时的颜色，稍浅的灰色 */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #455364; /* 鼠标点击时的颜色，稍深的灰色 */\n"
"}\n"
"")
        self.pt_select_button.setText("")
        self.pt_select_button.setIcon(icon)
        self.pt_select_button.setObjectName("pt_select_button")
        self.verticalLayout_4.addWidget(self.pt_select_button)
        self.model_select_button = QtWidgets.QPushButton(model_settings)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.model_select_button.sizePolicy().hasHeightForWidth())
        self.model_select_button.setSizePolicy(sizePolicy)
        self.model_select_button.setMinimumSize(QtCore.QSize(25, 0))
        self.model_select_button.setStyleSheet("QPushButton {\n"
"    background-color: #455364; /* 默认颜色，浅灰色 */\n"
"    border: 1px solid #666666; /* 灰色的边框 */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #54687a; /* 鼠标悬停时的颜色，稍浅的灰色 */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #455364; /* 鼠标点击时的颜色，稍深的灰色 */\n"
"}\n"
"")
        self.model_select_button.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("resources/op_icon/alarm.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.model_select_button.setIcon(icon1)
        self.model_select_button.setObjectName("model_select_button")
        self.verticalLayout_4.addWidget(self.model_select_button)
        self.labels_select_button = QtWidgets.QPushButton(model_settings)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labels_select_button.sizePolicy().hasHeightForWidth())
        self.labels_select_button.setSizePolicy(sizePolicy)
        self.labels_select_button.setMinimumSize(QtCore.QSize(25, 0))
        self.labels_select_button.setStyleSheet("QPushButton {\n"
"    background-color: #455364; /* 默认颜色，浅灰色 */\n"
"    border: 1px solid #666666; /* 灰色的边框 */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #54687a; /* 鼠标悬停时的颜色，稍浅的灰色 */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #455364; /* 鼠标点击时的颜色，稍深的灰色 */\n"
"}\n"
"")
        self.labels_select_button.setText("")
        self.labels_select_button.setIcon(icon)
        self.labels_select_button.setObjectName("labels_select_button")
        self.verticalLayout_4.addWidget(self.labels_select_button)
        self.max_size = QtWidgets.QPushButton(model_settings)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.max_size.sizePolicy().hasHeightForWidth())
        self.max_size.setSizePolicy(sizePolicy)
        self.max_size.setStyleSheet("QPushButton {\n"
"    background-color: #455364; /* 默认颜色，浅灰色 */\n"
"    border: 1px solid #666666; /* 灰色的边框 */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #54687a; /* 鼠标悬停时的颜色，稍浅的灰色 */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #455364; /* 鼠标点击时的颜色，稍深的灰色 */\n"
"}\n"
"")
        self.max_size.setText("")
        self.max_size.setIcon(icon1)
        self.max_size.setObjectName("max_size")
        self.verticalLayout_4.addWidget(self.max_size)
        self.conf = QtWidgets.QPushButton(model_settings)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.conf.sizePolicy().hasHeightForWidth())
        self.conf.setSizePolicy(sizePolicy)
        self.conf.setStyleSheet("QPushButton {\n"
"    background-color: #455364; /* 默认颜色，浅灰色 */\n"
"    border: 1px solid #666666; /* 灰色的边框 */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #54687a; /* 鼠标悬停时的颜色，稍浅的灰色 */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #455364; /* 鼠标点击时的颜色，稍深的灰色 */\n"
"}\n"
"")
        self.conf.setText("")
        self.conf.setIcon(icon1)
        self.conf.setObjectName("conf")
        self.verticalLayout_4.addWidget(self.conf)
        self.iou = QtWidgets.QPushButton(model_settings)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.iou.sizePolicy().hasHeightForWidth())
        self.iou.setSizePolicy(sizePolicy)
        self.iou.setStyleSheet("QPushButton {\n"
"    background-color: #455364; /* 默认颜色，浅灰色 */\n"
"    border: 1px solid #666666; /* 灰色的边框 */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #54687a; /* 鼠标悬停时的颜色，稍浅的灰色 */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #455364; /* 鼠标点击时的颜色，稍深的灰色 */\n"
"}\n"
"")
        self.iou.setText("")
        self.iou.setIcon(icon1)
        self.iou.setObjectName("iou")
        self.verticalLayout_4.addWidget(self.iou)
        self.line_thickness_button = QtWidgets.QPushButton(model_settings)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line_thickness_button.sizePolicy().hasHeightForWidth())
        self.line_thickness_button.setSizePolicy(sizePolicy)
        self.line_thickness_button.setStyleSheet("QPushButton {\n"
"    background-color: #455364; /* 默认颜色，浅灰色 */\n"
"    border: 1px solid #666666; /* 灰色的边框 */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #54687a; /* 鼠标悬停时的颜色，稍浅的灰色 */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #455364; /* 鼠标点击时的颜色，稍深的灰色 */\n"
"}\n"
"")
        self.line_thickness_button.setText("")
        self.line_thickness_button.setIcon(icon1)
        self.line_thickness_button.setObjectName("line_thickness_button")
        self.verticalLayout_4.addWidget(self.line_thickness_button)
        self.verticalLayout_4.setStretch(0, 1)
        self.verticalLayout_4.setStretch(1, 1)
        self.verticalLayout_4.setStretch(2, 1)
        self.verticalLayout_4.setStretch(3, 1)
        self.verticalLayout_4.setStretch(4, 1)
        self.verticalLayout_4.setStretch(5, 1)
        self.verticalLayout_4.setStretch(6, 1)
        self.horizontalLayout.addLayout(self.verticalLayout_4)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.label_5 = QtWidgets.QLabel(model_settings)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setStyleSheet("QPushButton {\n"
"    background-color: #455364; /* 默认颜色，浅灰色 */\n"
"    border: 1px solid #666666; /* 灰色的边框 */\n"
"    padding: 5px 10px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #54687a; /* 鼠标悬停时的颜色，稍浅的灰色 */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #455364; /* 鼠标点击时的颜色，稍深的灰色 */\n"
"}\n"
"")
        self.label_5.setText("")
        self.label_5.setObjectName("label_5")
        self.verticalLayout.addWidget(self.label_5)
        self.widget = QtWidgets.QWidget(model_settings)
        self.widget.setObjectName("widget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.widget)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setSpacing(0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setContentsMargins(10, -1, 10, -1)
        self.horizontalLayout_5.setSpacing(50)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_6 = QtWidgets.QLabel(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        self.label_6.setText("")
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_5.addWidget(self.label_6)
        self.save_button = QtWidgets.QPushButton(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.save_button.sizePolicy().hasHeightForWidth())
        self.save_button.setSizePolicy(sizePolicy)
        self.save_button.setMinimumSize(QtCore.QSize(40, 20))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(69, 83, 100))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(69, 83, 100))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(69, 83, 100))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(69, 83, 100))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(69, 83, 100))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(69, 83, 100))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(69, 83, 100))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(69, 83, 100))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(69, 83, 100))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.save_button.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.save_button.setFont(font)
        self.save_button.setAutoFillBackground(False)
        self.save_button.setStyleSheet("QPushButton {\n"
"    background-color: #455364; /* 默认颜色，浅灰色 */\n"
"    border: 1px solid #666666; /* 灰色的边框 */\n"
"    padding: 5px 10px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #54687a; /* 鼠标悬停时的颜色，稍浅的灰色 */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #455364; /* 鼠标点击时的颜色，稍深的灰色 */\n"
"}\n"
"")
        self.save_button.setObjectName("save_button")
        self.horizontalLayout_5.addWidget(self.save_button)
        self.begin = QtWidgets.QPushButton(self.widget)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(69, 83, 100))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(69, 83, 100))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(69, 83, 100))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(69, 83, 100))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(69, 83, 100))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(69, 83, 100))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(69, 83, 100))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(69, 83, 100))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(69, 83, 100))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.begin.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.begin.setFont(font)
        self.begin.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.begin.setStyleSheet("QPushButton {\n"
"    background-color: #455364; /* 默认颜色，浅灰色 */\n"
"    border: 1px solid #666666; /* 灰色的边框 */\n"
"    padding: 5px 10px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #54687a; /* 鼠标悬停时的颜色，稍浅的灰色 */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #455364; /* 鼠标点击时的颜色，稍深的灰色 */\n"
"}\n"
"")
        self.begin.setObjectName("begin")
        self.horizontalLayout_5.addWidget(self.begin)
        self.gridLayout_2.addLayout(self.horizontalLayout_5, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.widget)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)

        self.retranslateUi(model_settings)
        QtCore.QMetaObject.connectSlotsByName(model_settings)

    def retranslateUi(self, model_settings):
        _translate = QtCore.QCoreApplication.translate
        model_settings.setWindowTitle(_translate("model_settings", "Dialog"))
        self.label.setText(_translate("model_settings", "视频保存地址"))
        self.label_2.setText(_translate("model_settings", "选择权重"))
        self.label_3.setText(_translate("model_settings", "选择模型"))
        self.label_4.setText(_translate("model_settings", "标签集"))
        self.label_7.setText(_translate("model_settings", "最大识别数量"))
        self.label_8.setText(_translate("model_settings", "置信度"))
        self.label_9.setText(_translate("model_settings", "iou(交并比)"))
        self.label_10.setText(_translate("model_settings", "识别框线条大小"))
        self.model_combox.setItemText(0, _translate("model_settings", "yolo_slowfast"))
        self.model_combox.setItemText(1, _translate("model_settings", "yolov5"))
        self.max_size_comboBox.setItemText(0, _translate("model_settings", "10"))
        self.max_size_comboBox.setItemText(1, _translate("model_settings", "20"))
        self.max_size_comboBox.setItemText(2, _translate("model_settings", "40"))
        self.max_size_comboBox.setItemText(3, _translate("model_settings", "80"))
        self.max_size_comboBox.setItemText(4, _translate("model_settings", "100"))
        self.save_button.setText(_translate("model_settings", "保存"))
        self.begin.setText(_translate("model_settings", "开始识别"))
