# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'identifyResults_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_IdentifyResults(object):
    def setupUi(self, IdentifyResults):
        IdentifyResults.setObjectName("IdentifyResults")
        IdentifyResults.resize(813, 418)
        self.gridLayout = QtWidgets.QGridLayout(IdentifyResults)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.CardWidget_2 = CardWidget(IdentifyResults)
        self.CardWidget_2.setObjectName("CardWidget_2")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.CardWidget_2)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.expList = ListWidget(self.CardWidget_2)
        self.expList.setObjectName("expList")
        self.gridLayout_6.addWidget(self.expList, 0, 0, 1, 1)
        self.horizontalLayout.addWidget(self.CardWidget_2)
        self.CardWidget = CardWidget(IdentifyResults)
        self.CardWidget.setObjectName("CardWidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.CardWidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.SegmentedWidget = SegmentedWidget(self.CardWidget)
        self.SegmentedWidget.setObjectName("SegmentedWidget")
        self.verticalLayout.addWidget(self.SegmentedWidget)
        self.stackedWidget = QtWidgets.QStackedWidget(self.CardWidget)
        self.stackedWidget.setObjectName("stackedWidget")
        self.expWidget = QtWidgets.QWidget()
        self.expWidget.setObjectName("expWidget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.expWidget)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.exp_widget_2 = QtWidgets.QWidget(self.expWidget)
        self.exp_widget_2.setObjectName("exp_widget_2")
        self.gridLayout_28 = QtWidgets.QGridLayout(self.exp_widget_2)
        self.gridLayout_28.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_28.setSpacing(0)
        self.gridLayout_28.setObjectName("gridLayout_28")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.frame_6 = QtWidgets.QFrame(self.exp_widget_2)
        self.frame_6.setStyleSheet("#frame_5 {\n"
"    border: 1px solid rgba(255, 255, 255, 13);\n"
"    border-radius: 5px;\n"
"    background-color: transparent;\n"
"}")
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.frame_6)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.CardWidget_3 = CardWidget(self.frame_6)
        self.CardWidget_3.setObjectName("CardWidget_3")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.CardWidget_3)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.expItemList = ListWidget(self.CardWidget_3)
        self.expItemList.setObjectName("expItemList")
        self.gridLayout_7.addWidget(self.expItemList, 0, 0, 1, 1)
        self.gridLayout_4.addWidget(self.CardWidget_3, 0, 1, 1, 1)
        self.horizontalLayout_11.addWidget(self.frame_6)
        self.expplayer_2 = QtWidgets.QLabel(self.exp_widget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.expplayer_2.sizePolicy().hasHeightForWidth())
        self.expplayer_2.setSizePolicy(sizePolicy)
        self.expplayer_2.setStyleSheet("\n"
"        background: rgb(0, 0, 0);")
        self.expplayer_2.setText("")
        self.expplayer_2.setObjectName("expplayer_2")
        self.horizontalLayout_11.addWidget(self.expplayer_2)
        self.horizontalLayout_11.setStretch(0, 5)
        self.horizontalLayout_11.setStretch(1, 10)
        self.gridLayout_28.addLayout(self.horizontalLayout_11, 0, 0, 1, 1)
        self.horizontalLayout_10.addWidget(self.exp_widget_2)
        self.splitter_2 = QtWidgets.QSplitter(self.expWidget)
        self.splitter_2.setStyleSheet("            QSplitter {\n"
"                background-color: 19232d;\n"
"            }\n"
"            QSplitter::handle {\n"
"                background-color: 19232d;\n"
"            }")
        self.splitter_2.setOrientation(QtCore.Qt.Vertical)
        self.splitter_2.setObjectName("splitter_2")
        self.exp_inf_2 = TextEdit(self.splitter_2)
        self.exp_inf_2.setReadOnly(True)
        self.exp_inf_2.setObjectName("exp_inf_2")
        self.exp_type_2 = TextEdit(self.splitter_2)
        self.exp_type_2.setReadOnly(True)
        self.exp_type_2.setObjectName("exp_type_2")
        self.horizontalLayout_10.addWidget(self.splitter_2)
        self.gridLayout_3.addLayout(self.horizontalLayout_10, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.expWidget)
        self.PDFWidget = QtWidgets.QWidget()
        self.PDFWidget.setObjectName("PDFWidget")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.PDFWidget)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.gridLayout_8 = QtWidgets.QGridLayout()
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.gridLayout_5.addLayout(self.gridLayout_8, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.PDFWidget)
        self.verticalLayout.addWidget(self.stackedWidget)
        self.gridLayout_2.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.horizontalLayout.addWidget(self.CardWidget)
        self.horizontalLayout.setStretch(0, 1)
        self.horizontalLayout.setStretch(1, 4)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 0, 1, 1)

        self.retranslateUi(IdentifyResults)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(IdentifyResults)

    def retranslateUi(self, IdentifyResults):
        _translate = QtCore.QCoreApplication.translate
        IdentifyResults.setWindowTitle(_translate("IdentifyResults", "Form"))
from qfluentwidgets import CardWidget, ListWidget, SegmentedWidget, TextEdit
