# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'labels_settings_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_labels_settings(object):
    def setupUi(self, labels_settings):
        labels_settings.setObjectName("labels_settings")
        labels_settings.resize(582, 448)
        self.centralwidget = QtWidgets.QWidget(labels_settings)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.open = PushButton(self.centralwidget)
        self.open.setObjectName("open")
        self.horizontalLayout_4.addWidget(self.open)
        self.pushButton = PushButton(self.centralwidget)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_4.addWidget(self.pushButton)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.CardWidget = CardWidget(self.centralwidget)
        self.CardWidget.setObjectName("CardWidget")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.CardWidget)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.models_list = ListWidget(self.CardWidget)
        self.models_list.setStyleSheet("ListView,\n"
"ListWidget {\n"
"    background: transparent;\n"
"    outline: none;\n"
"    border: none;\n"
"    /* font: 13px \'Segoe UI\', \'Microsoft YaHei\'; */\n"
"    selection-background-color: transparent;\n"
"    alternate-background-color: transparent;\n"
"    padding-left: 4px;\n"
"    padding-right: 4px;\n"
"}\n"
"\n"
"ListView::item,\n"
"ListWidget::item {\n"
"    background: transparent;\n"
"    border: 0px;\n"
"    padding-left: 11px;\n"
"    padding-right: 11px;\n"
"    height: 35px;\n"
"}\n"
"\n"
"\n"
"ListView::indicator,\n"
"ListWidget::indicator {\n"
"    width: 18px;\n"
"    height: 18px;\n"
"    border-radius: 5px;\n"
"    border: none;\n"
"    background-color: transparent;\n"
"    margin-right: 4px;\n"
"}\n"
"\n"
"")
        self.models_list.setObjectName("models_list")
        self.gridLayout_5.addWidget(self.models_list, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.CardWidget)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButton_2 = PushButton(self.centralwidget)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout_2.addWidget(self.pushButton_2)
        self.delete_2 = PushButton(self.centralwidget)
        self.delete_2.setObjectName("delete_2")
        self.horizontalLayout_2.addWidget(self.delete_2)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.CardWidget_2 = CardWidget(self.centralwidget)
        self.CardWidget_2.setObjectName("CardWidget_2")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.CardWidget_2)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.sets_list = ListWidget(self.CardWidget_2)
        self.sets_list.setObjectName("sets_list")
        self.gridLayout_4.addWidget(self.sets_list, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.CardWidget_2)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.CardWidget_3 = CardWidget(self.centralwidget)
        self.CardWidget_3.setObjectName("CardWidget_3")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.CardWidget_3)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.SmoothScrollArea = SmoothScrollArea(self.CardWidget_3)
        self.SmoothScrollArea.setWidgetResizable(True)
        self.SmoothScrollArea.setObjectName("SmoothScrollArea")
        self.scrollAreaWidgetContents_3 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_3.setGeometry(QtCore.QRect(0, 0, 348, 388))
        self.scrollAreaWidgetContents_3.setObjectName("scrollAreaWidgetContents_3")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents_3)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.fan = PushButton(self.scrollAreaWidgetContents_3)
        self.fan.setObjectName("fan")
        self.horizontalLayout_6.addWidget(self.fan)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem)
        self.verticalLayout_2.addLayout(self.horizontalLayout_6)
        self.widget = QtWidgets.QWidget(self.scrollAreaWidgetContents_3)
        self.widget.setObjectName("widget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.widget)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.labels_part_2 = QtWidgets.QGridLayout()
        self.labels_part_2.setObjectName("labels_part_2")
        self.gridLayout_3.addLayout(self.labels_part_2, 0, 0, 1, 1)
        self.verticalLayout_2.addWidget(self.widget)
        self.verticalLayout_2.setStretch(1, 1)
        self.gridLayout_2.addLayout(self.verticalLayout_2, 0, 0, 1, 1)
        self.SmoothScrollArea.setWidget(self.scrollAreaWidgetContents_3)
        self.gridLayout_6.addWidget(self.SmoothScrollArea, 0, 0, 1, 1)
        self.horizontalLayout.addWidget(self.CardWidget_3)
        self.horizontalLayout.setStretch(0, 1)
        self.horizontalLayout.setStretch(1, 4)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        labels_settings.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(labels_settings)
        self.statusbar.setObjectName("statusbar")
        labels_settings.setStatusBar(self.statusbar)

        self.retranslateUi(labels_settings)
        QtCore.QMetaObject.connectSlotsByName(labels_settings)

    def retranslateUi(self, labels_settings):
        _translate = QtCore.QCoreApplication.translate
        labels_settings.setWindowTitle(_translate("labels_settings", "MainWindow"))
        self.open.setText(_translate("labels_settings", "打开文件夹"))
        self.pushButton.setText(_translate("labels_settings", "显示内容"))
        self.pushButton_2.setText(_translate("labels_settings", "新建"))
        self.delete_2.setText(_translate("labels_settings", "删除"))
        self.fan.setText(_translate("labels_settings", "反选"))
from qfluentwidgets import CardWidget, ListWidget, PushButton, SmoothScrollArea
