# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'testui.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(760, 602)
        self.gridLayout_2 = QtWidgets.QGridLayout(Form)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.CaptionLabel = CaptionLabel(Form)
        self.CaptionLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.CaptionLabel.setObjectName("CaptionLabel")
        self.horizontalLayout.addWidget(self.CaptionLabel)
        self.ComboBox = ComboBox(Form)
        self.ComboBox.setObjectName("ComboBox")
        self.horizontalLayout.addWidget(self.ComboBox)
        self.horizontalLayout.setStretch(1, 1)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.CaptionLabel_2 = CaptionLabel(Form)
        self.CaptionLabel_2.setObjectName("CaptionLabel_2")
        self.horizontalLayout_2.addWidget(self.CaptionLabel_2)
        self.ComboBox_3 = ComboBox(Form)
        self.ComboBox_3.setObjectName("ComboBox_3")
        self.horizontalLayout_2.addWidget(self.ComboBox_3)
        self.ComboBox_2 = ComboBox(Form)
        self.ComboBox_2.setObjectName("ComboBox_2")
        self.horizontalLayout_2.addWidget(self.ComboBox_2)
        self.horizontalLayout_2.setStretch(1, 2)
        self.horizontalLayout_2.setStretch(2, 5)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.TextEdit = TextEdit(Form)
        self.TextEdit.setObjectName("TextEdit")
        self.verticalLayout_2.addWidget(self.TextEdit)
        self.CardWidget_2 = CardWidget(Form)
        self.CardWidget_2.setObjectName("CardWidget_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.CardWidget_2)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.ListWidget = ListWidget(self.CardWidget_2)
        self.ListWidget.setObjectName("ListWidget")
        self.gridLayout_3.addWidget(self.ListWidget, 0, 0, 1, 1)
        self.verticalLayout_2.addWidget(self.CardWidget_2)
        self.verticalLayout_2.setStretch(1, 1)
        self.horizontalLayout_3.addLayout(self.verticalLayout_2)
        self.CardWidget_3 = CardWidget(Form)
        self.CardWidget_3.setObjectName("CardWidget_3")
        self.gridLayout = QtWidgets.QGridLayout(self.CardWidget_3)
        self.gridLayout.setObjectName("gridLayout")
        self.player_2 = QtWidgets.QWidget(self.CardWidget_3)
        self.player_2.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.player_2.setObjectName("player_2")
        self.gridLayout_18 = QtWidgets.QGridLayout(self.player_2)
        self.gridLayout_18.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_18.setHorizontalSpacing(6)
        self.gridLayout_18.setObjectName("gridLayout_18")
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.camera_2 = QtWidgets.QLabel(self.player_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.camera_2.sizePolicy().hasHeightForWidth())
        self.camera_2.setSizePolicy(sizePolicy)
        self.camera_2.setStyleSheet("\n"
"        background: rgb(0, 0, 0);")
        self.camera_2.setText("")
        self.camera_2.setObjectName("camera_2")
        self.horizontalLayout_17.addWidget(self.camera_2)
        self.gridLayout_18.addLayout(self.horizontalLayout_17, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.player_2, 2, 0, 1, 1)
        self.PushButton = PushButton(self.CardWidget_3)
        self.PushButton.setObjectName("PushButton")
        self.gridLayout.addWidget(self.PushButton, 3, 0, 1, 1)
        self.SubtitleLabel = SubtitleLabel(self.CardWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SubtitleLabel.sizePolicy().hasHeightForWidth())
        self.SubtitleLabel.setSizePolicy(sizePolicy)
        self.SubtitleLabel.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.SubtitleLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.SubtitleLabel.setObjectName("SubtitleLabel")
        self.gridLayout.addWidget(self.SubtitleLabel, 1, 0, 1, 1)
        self.horizontalLayout_3.addWidget(self.CardWidget_3)
        self.horizontalLayout_3.setStretch(0, 2)
        self.horizontalLayout_3.setStretch(1, 5)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.verticalLayout.setStretch(3, 1)
        self.gridLayout_2.addLayout(self.verticalLayout, 0, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.CaptionLabel.setText(_translate("Form", "   疾病分类    "))
        self.CaptionLabel_2.setText(_translate("Form", "定制模型分类"))
        self.TextEdit.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Segoe UI\',\'Microsoft YaHei\',\'PingFang SC\',\'SimSun\'; font-size:14px; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:11pt;\">PVC(聚氯乙烯):这是一种常用的塑料材料，轻便且耐用，易于清洁，成本相对较低。PVC制成的模型适合基础教育和展示使用，可以详细地展示脊柱的各个部分，包括椎骨、椎间盘等结构。←</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:11pt;\">树脂材料:树脂材质的模型比 PVC 更耐用，质感也更接近真实骨头，细节表现更为精细适合医疗教学和高级解剖学研究。它允许制作更复杂的结构，包括透明或半透明的椎间盘以展示内部构造。“</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:11pt;\">ABS 塑料:ABS 是一种强度高、韧性好、耐冲击的热塑性塑料，常用于制作高质量的教学模型，它的耐久性和细节再现能力较好。←</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:11pt;\">不锈钢或金属合金:一些高端或专业模型可能会采用金属材质，尤其是脊柱手术训练模型6复合材料:为了结合不同材质的优点，一些模型可能采用多种材料的复合结构，比如内部使用金属框架增加稳定性，外部覆盖 PVC 或树脂以呈现细节硅橡胶材料←</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:11pt;\">硬质发泡聚氨酯材料</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:11pt;\">硬质密实树脂材料←</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:11pt;\">K1</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:11pt;\">型号，一</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:11pt;\">ZC-121-A\\B←</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:11pt;\">尺寸:通用尺寸，定制尺寸。4</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:11pt;\">通用尺寸:自然大的模型:33x25x85厘米(长x宽x高)</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:11pt;\">人体脊柱模型:总长度为 80 厘米←</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:11pt;\">1:2缩小模型:16.5*12.5*47.5 厘米←</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:11pt;\">1:4缩小模型:8.25*6.25*21.25 厘米-定制尺寸:xx，xx，xx 厘米</span></p></body></html>"))
        self.PushButton.setText(_translate("Form", "下一步"))
        self.SubtitleLabel.setText(_translate("Form", "阅片区"))
from qfluentwidgets import CaptionLabel, CardWidget, ComboBox, ListWidget, PushButton, SubtitleLabel, TextEdit
