# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'users_widget_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_users_widget(object):
    def setupUi(self, users_widget):
        users_widget.setObjectName("users_widget")
        users_widget.resize(561, 470)
        self.gridLayout = QtWidgets.QGridLayout(users_widget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.SmoothScrollArea = SmoothScrollArea(users_widget)
        self.SmoothScrollArea.setWidgetResizable(True)
        self.SmoothScrollArea.setObjectName("SmoothScrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 559, 468))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("微软雅黑 Light")
        font.setPointSize(33)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.AvatarWidget = AvatarWidget(self.scrollAreaWidgetContents)
        self.AvatarWidget.setObjectName("AvatarWidget")
        self.horizontalLayout.addWidget(self.AvatarWidget)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.tableWidget = TableWidget(self.scrollAreaWidgetContents)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(3)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        self.verticalLayout.addWidget(self.tableWidget)
        self.gridLayout_2.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.SmoothScrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout.addWidget(self.SmoothScrollArea, 0, 1, 1, 1)

        self.retranslateUi(users_widget)
        QtCore.QMetaObject.connectSlotsByName(users_widget)

    def retranslateUi(self, users_widget):
        _translate = QtCore.QCoreApplication.translate
        users_widget.setWindowTitle(_translate("users_widget", "Form"))
        self.label.setText(_translate("users_widget", "用户"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("users_widget", "用户名"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("users_widget", "权限"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("users_widget", "操作"))
from qfluentwidgets import AvatarWidget, SmoothScrollArea, TableWidget
