# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'video_widget.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_video_widget(object):
    def setupUi(self, video_widget):
        video_widget.setObjectName("video_widget")
        video_widget.resize(379, 233)
        self.gridLayout = QtWidgets.QGridLayout(video_widget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.player_widget = CardWidget(video_widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.player_widget.sizePolicy().hasHeightForWidth())
        self.player_widget.setSizePolicy(sizePolicy)
        self.player_widget.setObjectName("player_widget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.player_widget)
        self.gridLayout_2.setContentsMargins(5, 5, 5, 5)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.frame = QtWidgets.QFrame(self.player_widget)
        self.frame.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.frame.setStyleSheet("QFrame {\n"
"    background-color: rgb(25, 25, 25);\n"
"}\n"
"QFrame:focus {\n"
"    background-color: rgb(25, 25, 25);\n"
"    border: 1px solid #29f1ff;\n"
"    color: white;\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setSpacing(0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.player_show = QtWidgets.QLabel(self.frame)
        self.player_show.setFocusPolicy(QtCore.Qt.NoFocus)
        self.player_show.setStyleSheet("background-color: rgb(25, 25, 25);")
        self.player_show.setText("")
        self.player_show.setObjectName("player_show")
        self.gridLayout_3.addWidget(self.player_show, 0, 0, 1, 1)
        self.gridLayout_2.addWidget(self.frame, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.player_widget, 0, 0, 1, 1)

        self.retranslateUi(video_widget)
        QtCore.QMetaObject.connectSlotsByName(video_widget)

    def retranslateUi(self, video_widget):
        _translate = QtCore.QCoreApplication.translate
        video_widget.setWindowTitle(_translate("video_widget", "Form"))
from qfluentwidgets import CardWidget
