item {  
  name: "person"  
  id: 0  
}  
item {  
  name: "bicycle"  
  id: 1  
}  
item {  
  name: "car"  
  id: 2  
}  
item {  
  name: "motorbike"  
  id: 3  
}  
item {  
  name: "aeroplane"  
  id: 4  
}  
item {  
  name: "bus"  
  id: 5  
}  
item {  
  name: "train"  
  id: 6  
}  
item {  
  name: "truck"  
  id: 7  
}  
item {  
  name: "boat"  
  id: 8  
}  
item {  
  name: "traffic light"  
  id: 9  
}  
item {  
  name: "fire hydrant"  
  id: 10  
}  
item {  
  name: "stop sign"  
  id: 11  
}  
item {  
  name: "parking meter"  
  id: 12  
}  
item {  
  name: "bench"  
  id: 13  
}  
item {  
  name: "bird"  
  id: 14  
}  
item {  
  name: "cat"  
  id: 15  
}  
item {  
  name: "dog"  
  id: 16  
}  
item {  
  name: "horse"  
  id: 17  
}  
item {  
  name: "sheep"  
  id: 18  
}  
item {  
  name: "cow"  
  id: 19  
}  
item {  
  name: "elephant"  
  id: 20  
}  
item {  
  name: "bear"  
  id: 21  
}  
item {  
  name: "zebra"  
  id: 22  
}  
item {  
  name: "giraffe"  
  id: 23  
}  
item {  
  name: "backpack"  
  id: 24  
}  
item {  
  name: "umbrella"  
  id: 25  
}
item {  
  name: "handbag"  
  id: 26  
}  
item {  
  name: "tie"  
  id: 27  
}  
item {  
  name: "suitcase"  
  id: 28  
}  
item {  
  name: "frisbee"  
  id: 29  
}  
item {  
  name: "skis"  
  id: 30  
}  
item {  
  name: "snowboard"  
  id: 31  
}  
item {  
  name: "sports ball"  
  id: 32  
}  
item {  
  name: "kite"  
  id: 33  
}  
item {  
  name: "baseball bat"  
  id: 34  
}  
item {  
  name: "baseball glove"  
  id: 35  
}  
item {  
  name: "skateboard"  
  id: 36  
}  
item {  
  name: "surfboard"  
  id: 37  
}  
item {  
  name: "tennis racket"  
  id: 38  
}  
item {  
  name: "bottle"  
  id: 39  
}  
item {  
  name: "wine glass"  
  id: 40  
}  
item {  
  name: "cup"  
  id: 41  
}  
item {  
  name: "fork"  
  id: 42  
}  
item {  
  name: "knife"  
  id: 43  
}  
item {  
  name: "spoon"  
  id: 44  
}  
item {  
  name: "bowl"  
  id: 45  
}
item {  
  name: "banana"  
  id: 46  
}  
item {  
  name: "apple"  
  id: 47  
}  
item {  
  name: "sandwich"  
  id: 48  
}  
item {  
  name: "orange"  
  id: 49  
}  
item {  
  name: "broccoli"  
  id: 50  
}  
item {  
  name: "carrot"  
  id: 51  
}  
item {  
  name: "hot dog"  
  id: 52  
}  
item {  
  name: "pizza"  
  id: 53  
}  
item {  
  name: "donut"  
  id: 54  
}  
item {  
  name: "cake"  
  id: 55  
}  
item {  
  name: "chair"  
  id: 56  
}  
item {  
  name: "sofa"  
  id: 57  
}  
item {  
  name: "pottedplant"  
  id: 58  
}  
item {  
  name: "bed"  
  id: 59  
}
item {  
  name: "diningtable"  
  id: 60  
}  
item {  
  name: "toilet"  
  id: 61  
}  
item {  
  name: "tvmonitor"  
  id: 62  
}  
item {  
  name: "laptop"  
  id: 63  
}  
item {  
  name: "mouse"  
  id: 64  
}  
item {  
  name: "remote"  
  id: 65  
}  
item {  
  name: "keyboard"  
  id: 66  
}  
item {  
  name: "cell phone"  
  id: 67  
}  
item {  
  name: "microwave"  
  id: 68  
}  
item {  
  name: "oven"  
  id: 69  
}  
item {  
  name: "toaster"  
  id: 70  
}  
item {  
  name: "sink"  
  id: 71  
}  
item {  
  name: "refrigerator"  
  id: 72  
}  
item {  
  name: "book"  
  id: 73  
}  
item {  
  name: "clock"  
  id: 74  
}
item {  
  name: "vase"  
  id: 75  
}  
item {  
  name: "scissors"  
  id: 76  
}  
item {  
  name: "teddy bear"  
  id: 77  
}  
item {  
  name: "hair drier"  
  id: 78  
}  
item {  
  name: "toothbrush"  
  id: 79  
}

